---

- name: Ensure NVM installation temp path exists
  become: true
  become_user: "{{ nvm_user }}"
  file:
    path: "{{ nvm_tmp_path }}"
    state: directory

- name: Download NVM installation script
  become: true
  become_user: "{{ nvm_user }}"
  get_url:
    dest: "{{ nvm_tmp_path }}"
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh

- name: Set installation script permissions
  become: true
  become_user: "{{ nvm_user }}"
  file:
    path: "{{ nvm_tmp_path }}/install.sh"
    mode: 0755

- name: Set nvm script permissions
  become: true
  become_user: "{{ nvm_user }}"
  file:
    path: "{{ nvm_tmp_path }}/nvm.sh"
    mode: 0755

- name: Run NVM installation script
  become: true
  become_user: "{{ nvm_user }}"
  command: "bash {{ nvm_tmp_path }}/install.sh"
  args:
    creates: "{{ nvm_dir }}"
    chdir: "{{ nvm_tmp_path }}"

- name: Delete NVM installation temp
  become: true
  become_user: "{{ nvm_user }}"
  file:
    path: "{{ nvm_tmp_path }}"
    state: absent
