---

- name: Does NVM already exists?
  stat:
    path: "{{ nvm_install_dir }}"
  register: nvm_st

- name: Download NVM installation script
  get_url:
    dest: "{{ nvm_home }}"
    url: https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh
  when: not nvm_st.stat.exists

- name: Run NVM installation script
  command: "{{ nvm_home }}/install.sh"
  args:
    creates: "{{ nvm_install_dir }}"
    chdir: "{{ nvm_home }}"
  when: not nvm_st.stat.exists
