---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"
      - "default.yml"
      paths: vars

# Check if NMV directory already exists
- name: Does NVM already exists?
  stat:
    path: "{{ nvm_dir }}"
  become: true
  become_user: "{{ nvm_user }}"
  register: nvm_st

# Install NVM
- import_tasks: install.yml
  when: not nvm_st.stat.exists

# Configure shell
- import_tasks: shell.yml
  when: nvm_shell_init

# Install default Node.js versions
- import_tasks: versions.yml

# Install default/global NPM packages
- import_tasks: npm.yml
