---

- name: Load variables for the target system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- include: install.yml

# Configure shell
- include: shell.yml
  when: nvm_shell_init

# Install default Node.js versions
- include: versions.yml

# Install default NPM packages
- include: npm.yml
